import { readFile, writeFile } from "node:fs/promises";

// Run with: node --import tsx scripts/bundle-card-fonts.ts
const lines = ["// Outfit, SIL Open Font License; see OFL.txt.", "// Generated by scripts/bundle-card-fonts.ts; inline WOFFs survive Eve bundling."];
for (const [name, weight] of [["outfitRegular", 400], ["outfitBold", 700]] as const) {
  const bytes = await readFile(new URL(import.meta.resolve(`@fontsource/outfit/files/outfit-latin-${weight}-normal.woff`)));
  lines.push(`export const ${name} = ${JSON.stringify(bytes.toString("base64"))};`);
}
await writeFile(new URL("../src/visual/assets/outfit.ts", import.meta.url), `${lines.join("\n")}\n`);
